# ========================================
# MBC Application - Test Environment
# ========================================

server:
  port: 8081
  servlet:
    context-path: /mbc

spring:
  application:
    name: mbc-application-test

  # Database Configuration (H2 File for Testing)
  datasource:
    url: jdbc:h2:file:./data/mbcdb_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 15000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # H2 Console (Test Environment)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false

  # Jackson Configuration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kbstar.mbc.dc.dto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false

# Logging Configuration
logging:
  level:
    root: INFO
    com.kbstar.mbc: DEBUG
    com.kbstar.ksa: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.mybatis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mbc-application-test.log
    max-size: 50MB
    max-history: 7

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: list
    disable-swagger-default-url: true
  packages-to-scan: com.kbstar.mbc.ac, com.kbstar.mbc.controller
  paths-to-match: /api/**, /mbc/**

# Security Configuration (Test - Relaxed)
spring:
  security:
    user:
      name: test
      password: test123
      roles: USER

# Application Configuration
app:
  environment: test
  debug: true
  data-access:
    type: mybatis
    description: "테스트 환경 - MyBatis 데이터 접근 방식"
  
  # Database Initialization
  database:
    initialize: true
    schema-location: classpath:schema.sql
    data-location: classpath:data.sql
    
  # API Configuration
  api:
    version: v1
    base-path: /api/v1
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      
  # Monitoring
  monitoring:
    enabled: true
    health-check-interval: 30s
    
# MBC Specific Configuration
mbc:
  system:
    name: "MBC Test System"
    version: "1.0.0-TEST"
    description: "Management Business Control - Test Environment"
  
  # Business Logic Configuration
  business:
    transaction-timeout: 30
    max-retry-count: 2
    audit-logging: true
    
  # Integration Configuration
  integration:
    external-api:
      timeout: 3000
      retry-count: 1
    messaging:
      enabled: false
      
  # Cache Configuration
  cache:
    enabled: false
    ttl: 60 # 1 minute
    max-size: 100 