spring:
  application:
    name: mbc-application

  # Profile Configuration
  profiles:
    active: dev # 기본값: dev, prod로 변경 가능

  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Jackson Configuration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    default-property-inclusion: non_null

  # DevTools Configuration (비활성화)
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /mbc

# Logging Configuration
logging:
  level:
    com.kbstar.mbc: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mbc-application.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Application Configuration
app:
  data-access:
    type: jdbc # jdbc로 변경
    description: "데이터 접근 방식 설정 (jdbc)"

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  packages-to-scan: com.kbstar.mbc.ac
  paths-to-match: /api/**
