spring:
  datasource:
    url: jdbc:h2:mem:mbcdb_dev
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.kbstar.mbc: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Development specific settings
mbc:
  environment: development
  debug: true
