-- MBC 시스템 데이터베이스 스키마
-- 생성일: 2024년
-- 설명: MBC 시스템의 기본 테이블 구조

-- 사용자 정보 테이블
CREATE TABLE IF NOT EXISTS USER_INFO (
    USER_ID VARCHAR(50) PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    ROLE VARCHAR(20) NOT NULL DEFAULT 'USER',
    STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ACCOUNT 테이블 생성
CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNT_NUMBER VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    IDENTIFICATION_NUMBER VARCHAR(14) NOT NULL,
    INTEREST_RATE DECIMAL(5,2),
    LAST_TRANSACTION TIMESTAMP,
    PASSWORD VARCHAR(100) NOT NULL,
    NET_AMOUNT VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 사용자-계정 연결 테이블
CREATE TABLE IF NOT EXISTS USER_ACCOUNT (
    USER_ID VARCHAR(50) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
    RELATION_TYPE VARCHAR(20) DEFAULT 'OWNER',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, ACCOUNT_NUMBER),
    FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER) ON DELETE CASCADE
);

-- 시스템 코드 테이블
CREATE TABLE IF NOT EXISTS SYSTEM_CODE (
    CODE_ID VARCHAR(50) PRIMARY KEY,
    CODE_TYPE VARCHAR(50) NOT NULL,
    CODE_VALUE VARCHAR(100) NOT NULL,
    CODE_NAME VARCHAR(200) NOT NULL,
    CODE_DESC TEXT,
    SORT_ORDER INT DEFAULT 0,
    USE_YN VARCHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (CODE_TYPE, CODE_VALUE)
);

-- 거래 내역 테이블
CREATE TABLE IF NOT EXISTS TRANSACTION (
    TRANSACTION_ID VARCHAR(50) PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    AMOUNT DECIMAL(15,2) NOT NULL,
    CURRENCY VARCHAR(3) DEFAULT 'KRW',
    DESCRIPTION TEXT,
    STATUS VARCHAR(10) DEFAULT 'COMPLETED',
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER) ON DELETE CASCADE
);

-- 메뉴 정보 테이블
CREATE TABLE IF NOT EXISTS MENU (
    MENU_ID VARCHAR(50) PRIMARY KEY,
    MENU_NAME VARCHAR(100) NOT NULL,
    MENU_URL VARCHAR(200),
    PARENT_MENU_ID VARCHAR(50),
    SORT_ORDER INT DEFAULT 0,
    USE_YN VARCHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PARENT_MENU_ID) REFERENCES MENU(MENU_ID) ON DELETE SET NULL
);

-- 역할 정보 테이블
CREATE TABLE IF NOT EXISTS ROLE (
    ROLE_ID VARCHAR(50) PRIMARY KEY,
    ROLE_NAME VARCHAR(100) NOT NULL,
    ROLE_DESC TEXT,
    USE_YN VARCHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 사용자 역할 연결 테이블
CREATE TABLE IF NOT EXISTS USER_ROLE (
    USER_ID VARCHAR(50) NOT NULL,
    ROLE_ID VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID) ON DELETE CASCADE
);

-- 역할 메뉴 권한 테이블
CREATE TABLE IF NOT EXISTS ROLE_MENU (
    ROLE_ID VARCHAR(50) NOT NULL,
    MENU_ID VARCHAR(50) NOT NULL,
    PERMISSION_TYPE VARCHAR(20) DEFAULT 'READ',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_ID, MENU_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID) ON DELETE CASCADE,
    FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID) ON DELETE CASCADE
);

-- 로그 테이블
CREATE TABLE IF NOT EXISTS SYSTEM_LOG (
    LOG_ID VARCHAR(50) PRIMARY KEY,
    USER_ID VARCHAR(50),
    LOG_TYPE VARCHAR(20) NOT NULL,
    LOG_LEVEL VARCHAR(10) DEFAULT 'INFO',
    MESSAGE TEXT NOT NULL,
    IP_ADDRESS VARCHAR(45),
    USER_AGENT TEXT,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID) ON DELETE SET NULL
);

-- 설정 테이블
CREATE TABLE IF NOT EXISTS SYSTEM_CONFIG (
    CONFIG_ID VARCHAR(50) PRIMARY KEY,
    CONFIG_KEY VARCHAR(100) UNIQUE NOT NULL,
    CONFIG_VALUE TEXT,
    CONFIG_DESC TEXT,
    USE_YN VARCHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 파일 정보 테이블
CREATE TABLE IF NOT EXISTS FILE_INFO (
    FILE_ID VARCHAR(50) PRIMARY KEY,
    FILE_NAME VARCHAR(200) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_SIZE BIGINT,
    FILE_TYPE VARCHAR(100),
    UPLOAD_USER_ID VARCHAR(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UPLOAD_USER_ID) REFERENCES USER_INFO(USER_ID) ON DELETE SET NULL
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS IDX_USER_INFO_EMAIL ON USER_INFO(EMAIL);
CREATE INDEX IF NOT EXISTS IDX_USER_INFO_ROLE ON USER_INFO(ROLE);
CREATE INDEX IF NOT EXISTS IDX_USER_INFO_STATUS ON USER_INFO(STATUS);

CREATE INDEX IF NOT EXISTS IDX_ACCOUNT_NAME ON ACCOUNT(NAME);
CREATE INDEX IF NOT EXISTS IDX_ACCOUNT_IDENTIFICATION ON ACCOUNT(IDENTIFICATION_NUMBER);

CREATE INDEX IF NOT EXISTS IDX_SYSTEM_CODE_TYPE ON SYSTEM_CODE(CODE_TYPE);
CREATE INDEX IF NOT EXISTS IDX_SYSTEM_CODE_USE_YN ON SYSTEM_CODE(USE_YN);

CREATE INDEX IF NOT EXISTS IDX_TRANSACTION_ACCOUNT ON TRANSACTION(ACCOUNT_NUMBER);
CREATE INDEX IF NOT EXISTS IDX_TRANSACTION_DATE ON TRANSACTION(TRANSACTION_DATE);
CREATE INDEX IF NOT EXISTS IDX_TRANSACTION_TYPE ON TRANSACTION(TRANSACTION_TYPE);

CREATE INDEX IF NOT EXISTS IDX_SYSTEM_LOG_USER ON SYSTEM_LOG(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_SYSTEM_LOG_TYPE ON SYSTEM_LOG(LOG_TYPE);
CREATE INDEX IF NOT EXISTS IDX_SYSTEM_LOG_DATE ON SYSTEM_LOG(CREATED_DATE);

CREATE INDEX IF NOT EXISTS IDX_SYSTEM_CONFIG_KEY ON SYSTEM_CONFIG(CONFIG_KEY); 