-- ========================================
-- MBC Project Database Schema
-- SKAX Project Eplaton
-- ========================================

-- 계정 테이블
CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNT_ID VARCHAR(20) PRIMARY KEY,
    ACCOUNT_NAME VARCHAR(100) NOT NULL,
    ACCOUNT_TYPE VARCHAR(20) DEFAULT 'NORMAL',
    BALANCE DECIMAL(15,2) DEFAULT 0.00,
    STATUS VARCHAR(10) DEFAULT 'ACTIVE',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM'
);

-- 사용자 테이블
CREATE TABLE IF NOT EXISTS USER_INFO (
    USER_ID VARCHAR(20) PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    DEPARTMENT VARCHAR(50),
    ROLE VARCHAR(20) DEFAULT 'USER',
    STATUS VARCHAR(10) DEFAULT 'ACTIVE',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(50) DEFAULT 'SYSTEM'
);

-- 사용자 계정 매핑 테이블
CREATE TABLE IF NOT EXISTS USER_ACCOUNT (
    USER_ID VARCHAR(20),
    ACCOUNT_ID VARCHAR(20),
    RELATIONSHIP_TYPE VARCHAR(20) DEFAULT 'OWNER',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, ACCOUNT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

-- 시스템 코드 테이블
CREATE TABLE IF NOT EXISTS SYSTEM_CODE (
    CODE_GROUP VARCHAR(50),
    CODE_VALUE VARCHAR(50),
    CODE_NAME VARCHAR(100) NOT NULL,
    CODE_DESC VARCHAR(200),
    SORT_ORDER INTEGER DEFAULT 0,
    USE_YN CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CODE_GROUP, CODE_VALUE)
);

-- 로그 테이블
CREATE TABLE IF NOT EXISTS SYSTEM_LOG (
    LOG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    LOG_LEVEL VARCHAR(10) NOT NULL,
    LOG_MESSAGE TEXT,
    LOG_CLASS VARCHAR(200),
    LOG_METHOD VARCHAR(100),
    USER_ID VARCHAR(20),
    IP_ADDRESS VARCHAR(45),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS IDX_ACCOUNT_STATUS ON ACCOUNT(STATUS);
CREATE INDEX IF NOT EXISTS IDX_USER_STATUS ON USER_INFO(STATUS);
CREATE INDEX IF NOT EXISTS IDX_USER_ACCOUNT_USER ON USER_ACCOUNT(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_USER_ACCOUNT_ACCOUNT ON USER_ACCOUNT(ACCOUNT_ID);
CREATE INDEX IF NOT EXISTS IDX_SYSTEM_LOG_DATE ON SYSTEM_LOG(CREATED_DATE);
CREATE INDEX IF NOT EXISTS IDX_SYSTEM_LOG_LEVEL ON SYSTEM_LOG(LOG_LEVEL); 